// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdoEdeUbz8Yy6VlaX0N9dxV8pPZI2poa4',
    appId: '1:657855669577:android:eb3e21d9c296f5244a2698',
    messagingSenderId: '657855669577',
    projectId: 'mynotes-whitemanoc',
    storageBucket: 'mynotes-whitemanoc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHirQ5sB6pMYYulTMyjIDgEHSgZkW1k9A',
    appId: '1:657855669577:ios:09dacbbd05fe6e234a2698',
    messagingSenderId: '657855669577',
    projectId: 'mynotes-whitemanoc',
    storageBucket: 'mynotes-whitemanoc.appspot.com',
    iosClientId: '657855669577-3piaraeo9bus611ve0sc8o3setubvups.apps.googleusercontent.com',
    iosBundleId: 'com.example.mynotes',
  );
}
